In [231]:
import os
import numpy as np
import pandas as pd

In [232]:
#for converting it into table form
df=pd.read_csv(r"C:\Users\win-11\Desktop\data science\python\project\data.csv")

In [233]:
df

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [234]:
df.head() #bydefault give first 5 rows

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1

In [235]:
df.head(15) ## first 15 rows

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
5,5,5,Acer,Extensa EX214-53 Laptop,39990,62.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
6,6,6,Dell,Inspiron 3520 D560896WIN9B Laptop,36790,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
7,7,7,Acer,Nitro V ANV15-51 2023 Gaming Laptop,76990,63.000000,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR5,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
8,8,8,Asus,Vivobook 15 X1502ZA-EJ523WS Laptop,48990,64.000000,12th Gen Intel Core i5 12500H,"12 Cores (4P + 8E), 16 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe,15.6,1920.0,1080.0,Windows 11 OS,1
9,9,9,Samsung,Galaxy Book2 Pro 13 Laptop,74990,68.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Iris Xe Graphics,13.3,1080.0,1920.0,Windows 11 OS,1
10,10,10,Lenovo,V15 G3 IAP 82TTA08AIN Laptop,49990,69.323529,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16GB,DDR4,512GB,SSD,Intel Integrated UHD,15.6,1920.0,1080.0,Windows 11 OS,1
11,11,11,Ultimus,Pro NU14U3INC43BN-CS Laptop,10990,69.323529,Intel Celeron N4020,"Dual Core, 2 Threads",4GB,DDR4,128GB,SSD,Intel Integrated UHD Graphics,14.1,1366.0,768.0,Windows 11 OS,1
12,12,12,Asus,TUF Gaming F15 2022 FX507ZC4-HN116W Gaming Laptop,72990,76.000000,12th Gen Intel Core i5 12500H,"12 Cores (4P + 8E), 16 Threads",16GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,1
13,13,13,Primebook,4G Android Laptop,10990,69.323529,MediaTek MTK8788,Octa Core,4GB,LPDDR4,64GB,Hard-Disk,ARM Mali G72,11.6,1366.0,768.0,Android 11 OS,1
14,15,15,Lenovo,V15 G4 ‎82YU00W7IN Laptop,29990,69.323529,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",8GB,LPDDR5,512GB,SSD,AMD Radeon Graphics,15.6,1920.0,1080.0,Windows 11 OS,1

In [236]:
df.tail() ##last 5 items

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [237]:
df.tail(15) #3last 15 items

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
878,916,1005,MSI,Katana 15 B12UDXK-1019IN Gaming Laptop,79990,75.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",16GB,DDR5,1TB,SSD,6GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,2
879,917,1006,Acer,One 14 Z2-493 Business Laptop,29990,69.323529,3rd Gen AMD Ryzen 5 3500U,"Quad Core, 8 Threads",8GB,DDR4,512GB,SSD,AMD Radeon Radeon Graphics,14.0,1366.0,768.0,Windows 11 OS,1
880,918,1007,HP,Victus 15-fb0135AX Gaming Laptop,59990,64.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,1
881,919,1008,Acer,Swift Edge 16 2023 Laptop,107399,69.323529,7th Gen AMD Ryzen 7040 Series 040,"Octa Core, 16 Threads",16GB,LPDDR5,1TB,SSD,AMD Radeon AMD,16.0,3840.0,2400.0,Windows 11 OS,1
882,920,1009,Dell,G15-5530 Gaming 2023 Laptop,129199,76.000000,13th Gen Intel Core i7 13650HX,14 Cores (6P + 8E),16GB,DDR5,512GB,SSD,8GB NVIDIA GeForce RTX 4060,15.6,1920.0,1080.0,Windows 11 OS,1
883,921,1010,Dell,G15-5530 Gaming Laptop,119990,73.000000,13th Gen Intel Core i7 13650HX,14 Cores (6P + 8E),16GB,DDR5,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
884,922,1011,Dell,‎G16-7630 Gaming Laptop,187490,79.000000,13th Gen Intel Core i9 13900HX,"24 Cores (8P + 16E), 32 Threads",16GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,16.0,2560.0,1600.0,Windows 11 OS,1
885,923,1012,Dell,G15-5530 2023 Gaming Laptop,125699,75.000000,13th Gen Intel Core i7 13650HX,14 Cores (6P + 8E),16GB,DDR5,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
886,924,1013,Acer,Aspire Vero AV14-52P NX.KJTSI.002 Laptop,49990,69.323529,13th Gen Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",16GB,LPDDR4X,512GB,SSD,Intel Integrated UHD,14.0,1920.0,1080.0,Windows OS,1
887,925,1014,Acer,Aspire 5 A515-58M NX.KHGSI.002 Gaming Laptop,56990,69.323529,13th Gen Intel Core i5 1335U,"10 Cores (2P + 8E), 12 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,15.6,1920.0,1080.0,Windows 11 OS,1
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [238]:
df.info() ##for info

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   Ram_type           893 non-null    str
 10  ROM                893 non-null    str
 11  ROM_type           893 non-null    str
 12  GPU                893 non-null    str
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    str
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), str(10)
memory usage: 125.7 KB

In [239]:
df.columns ##for all columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'brand', 'name', 'price', 'spec_rating',
       'processor', 'CPU', 'Ram', 'Ram_type', 'ROM', 'ROM_type', 'GPU',
       'display_size', 'resolution_width', 'resolution_height', 'OS',
       'warranty'],
      dtype='str')

In [240]:
df[['CPU']] #to extrcat a column

                                CPU
0             Hexa Core, 12 Threads
1    Hexa Core (2P + 4E), 8 Threads
2              Dual Core, 4 Threads
3    12 Cores (4P + 8E), 16 Threads
4               Octa Core (4P + 4E)
..                              ...
888  Hexa Core (2P + 4E), 8 Threads
889           Octa Core, 16 Threads
890           Octa Core, 16 Threads
891  14 Cores (6P + 8E), 20 Threads
892           Octa Core, 16 Threads

[893 rows x 1 columns]

In [241]:
df[['price','brand']]

      price   brand
0     49900      HP
1     39900      HP
2     26990    Acer
3     59729  Lenovo
4     69990   Apple
..      ...     ...
888   44990    Asus
889  110000    Asus
890  189990    Asus
891  129990    Asus
892  131990    Asus

[893 rows x 2 columns]

In [242]:
df['brand'].unique() #brand name without repition

<StringArray>
[       'HP',      'Acer',    'Lenovo',     'Apple',      'Dell',      'Asus',
   'Samsung',   'Ultimus', 'Primebook',       'MSI',   'Infinix',     'Wings',
     'Honor', 'Zebronics',    'Xiaomi',     'iBall',     'Chuwi',    'Realme',
     'Avita',    'Walker',    'Huawei',     'Tecno',  'Gigabyte',      'Vaio',
 'Microsoft',   'Fujitsu',        'LG',   'Ninkear',     'Razer',       'AXL']
Length: 30, dtype: str

In [243]:
df['brand'].nunique()#no, of unique items

30

In [244]:
df['brand'].value_counts()# how many laptops of indidividual brand

brand
HP           186
Lenovo       169
Asus         157
Dell         107
Acer          84
MSI           65
Samsung       28
Apple         16
Infinix       15
LG             9
Xiaomi         8
Gigabyte       8
Fujitsu        6
Ultimus        4
Zebronics      4
Wings          3
Chuwi          3
Realme         3
Tecno          3
Honor          2
Huawei         2
Microsoft      2
AXL            2
Primebook      1
iBall          1
Avita          1
Walker         1
Vaio           1
Ninkear        1
Razer          1
Name: count, dtype: int64

In [245]:
df.duplicated().sum() #count duplicate values

np.int64(0)

In [246]:
df.drop_duplicates() ##temporarily deletes duplicate values
#this dont have duplicate value so same answer

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,1
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,1
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,1

In [247]:
df.drop_duplicates(inplace=True)#permanent deleting of dats

In [248]:
df.duplicated().sum()##to check if duplicate values are deleted or not

np.int64(0)

In [249]:
df.isnull() ##check for null values

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
891,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
892,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [250]:
df.isnull().sum() #count of nullvalues present

Unnamed: 0.1         0
Unnamed: 0           0
brand                0
name                 0
price                0
spec_rating          0
processor            0
CPU                  0
Ram                  0
Ram_type             0
ROM                  0
ROM_type             0
GPU                  0
display_size         0
resolution_width     0
resolution_height    0
OS                   0
warranty             0
dtype: int64

In [251]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   Ram_type           893 non-null    str
 10  ROM                893 non-null    str
 11  ROM_type           893 non-null    str
 12  GPU                893 non-null    str
 13  display_size       893 non-null    float64
 14  resolution_width   893 non-null    float64
 15  resolution_height  893 non-null    float64
 16  OS                 893 non-null    str
 17  warranty           893 non-null    int64
dtypes: float64(4), int64(4), str(10)
memory usage: 125.7 KB

In [252]:
df['OS'].unique()

<StringArray>
[     'Windows 11 OS',             'Mac OS',      'Android 11 OS',
             'DOS OS',      'Windows 10 OS',     'Windows 10  OS',
          'Chrome OS',         'Windows OS',          'Ubuntu OS',
    'Mac Catalina OS',         'DOS 3.0 OS',     'Windows 11  OS',
 'Mac High Sierra OS',   'Mac 10.15.3\t OS']
Length: 14, dtype: str

In [253]:
df['warranty'].unique()

array([1, 0, 2, 3])

In [254]:
warranty_dict={1:'one' ,0:'zero', #3to chng from int to string
2:'two',3:'three'}

In [255]:
df['warranty']=df['warranty'].map(warranty_dict)

In [256]:
df

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,one
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,one
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,DDR,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,one
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,DDR5,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,one
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,DDR4,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,DDR4,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one

In [257]:
df.drop('Ram_type',axis=1,inplace=True)

In [258]:
df

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,one
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
2,2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,one
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,44990,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,110000,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,one
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,189990,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,one
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,129990,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,131990,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one

In [259]:
#df.drop(['ROM_type','price'],axis=1,inplace=True)
#df

In [260]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0.1       893 non-null    int64
 1   Unnamed: 0         893 non-null    int64
 2   brand              893 non-null    str
 3   name               893 non-null    str
 4   price              893 non-null    int64
 5   spec_rating        893 non-null    float64
 6   processor          893 non-null    str
 7   CPU                893 non-null    str
 8   Ram                893 non-null    str
 9   ROM                893 non-null    str
 10  ROM_type           893 non-null    str
 11  GPU                893 non-null    str
 12  display_size       893 non-null    float64
 13  resolution_width   893 non-null    float64
 14  resolution_height  893 non-null    float64
 15  OS                 893 non-null    str
 16  warranty           893 non-null    str
dtypes: float64(4), int64(3), str(10)
memory usage: 118.7 KB

In [261]:
obj_val=df.select_dtypes(include='O') ##string wale attributes 
obj_val

C:\Users\win-11\AppData\Local\Temp\ipykernel_28228\1466044125.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_val=df.select_dtypes(include='O') ##string wale attributes

,brand,name,processor,CPU,Ram,ROM,ROM_type,GPU,OS,warranty
0,HP,Victus 15-fb0157AX Gaming Laptop,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,512GB,SSD,4GB AMD Radeon RX 6500M,Windows 11 OS,one
1,HP,15s-fq5007TU Laptop,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,512GB,SSD,Intel UHD Graphics,Windows 11 OS,one
2,Acer,One 14 Z8-415 Laptop,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,512GB,SSD,Intel Iris Xe Graphics,Windows 11 OS,one
3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,512GB,SSD,Intel Integrated Iris Xe,Windows 11 OS,one
4,Apple,MacBook Air 2020 MGND3HN Laptop,Apple M1,Octa Core (4P + 4E),8GB,256GB,SSD,Apple M1 Integrated Graphics,Mac OS,one
...,...,...,...,...,...,...,...,...,...,...
888,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,512GB,SSD,Integrated Intel UHD Graphics,Windows 11 OS,one
889,Asus,TUF A15 FA577RM-HQ032WS Laptop,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,1TB,SSD,6GB NVIDIA GeForce RTX 3060,Windows 11 OS,one
890,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,1TB,SSD,8GB NVIDIA GeForce RTX 4060,Windows 11 OS,one
891,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,512GB,SSD,6GB NVIDIA GeForce RTX 4050,Windows 11 OS,one
892,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,1TB,SSD,6GB NVIDIA GeForce RTX 4050,Windows 11 OS,one

In [262]:
num_val=df.select_dtypes(exclude='O') ##int and float wale attributes

In [263]:
num_val

,Unnamed: 0.1,Unnamed: 0,price,spec_rating,display_size,resolution_width,resolution_height
0,0,0,49900,73.000000,15.6,1920.0,1080.0
1,1,1,39900,60.000000,15.6,1920.0,1080.0
2,2,2,26990,69.323529,14.0,1920.0,1080.0
3,3,3,59729,66.000000,14.0,2240.0,1400.0
4,4,4,69990,69.323529,13.3,2560.0,1600.0
...,...,...,...,...,...,...,...
888,926,1015,44990,69.323529,15.6,1920.0,1080.0
889,927,1016,110000,71.000000,15.6,2560.0,1440.0
890,928,1017,189990,89.000000,14.0,2560.0,1600.0
891,929,1018,129990,73.000000,15.6,1920.0,1080.0
892,930,1019,131990,84.000000,15.6,1920.0,1080.0

In [264]:
complete_Data=pd.concat([obj_val,num_val],axis=1) ##all the attributes both stringd and int float
complete_Data

,brand,name,processor,CPU,Ram,ROM,ROM_type,GPU,OS,warranty,Unnamed: 0.1,Unnamed: 0,price,spec_rating,display_size,resolution_width,resolution_height
0,HP,Victus 15-fb0157AX Gaming Laptop,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,512GB,SSD,4GB AMD Radeon RX 6500M,Windows 11 OS,one,0,0,49900,73.000000,15.6,1920.0,1080.0
1,HP,15s-fq5007TU Laptop,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,512GB,SSD,Intel UHD Graphics,Windows 11 OS,one,1,1,39900,60.000000,15.6,1920.0,1080.0
2,Acer,One 14 Z8-415 Laptop,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,512GB,SSD,Intel Iris Xe Graphics,Windows 11 OS,one,2,2,26990,69.323529,14.0,1920.0,1080.0
3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,512GB,SSD,Intel Integrated Iris Xe,Windows 11 OS,one,3,3,59729,66.000000,14.0,2240.0,1400.0
4,Apple,MacBook Air 2020 MGND3HN Laptop,Apple M1,Octa Core (4P + 4E),8GB,256GB,SSD,Apple M1 Integrated Graphics,Mac OS,one,4,4,69990,69.323529,13.3,2560.0,1600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,512GB,SSD,Integrated Intel UHD Graphics,Windows 11 OS,one,926,1015,44990,69.323529,15.6,1920.0,1080.0
889,Asus,TUF A15 FA577RM-HQ032WS Laptop,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,1TB,SSD,6GB NVIDIA GeForce RTX 3060,Windows 11 OS,one,927,1016,110000,71.000000,15.6,2560.0,1440.0
890,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,1TB,SSD,8GB NVIDIA GeForce RTX 4060,Windows 11 OS,one,928,1017,189990,89.000000,14.0,2560.0,1600.0
891,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,512GB,SSD,6GB NVIDIA GeForce RTX 4050,Windows 11 OS,one,929,1018,129990,73.000000,15.6,1920.0,1080.0
892,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,1TB,SSD,6GB NVIDIA GeForce RTX 4050,Windows 11 OS,one,930,1019,131990,84.000000,15.6,1920.0,1080.0

In [265]:
hp_brand=df[df['brand']=="HP"] ##filteringggggg
hp_brand

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,one
1,1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
18,19,19,HP,Victus 15-fa0666TX Gaming Laptop,68990,65.000000,12th Gen Intel Core i5 12450H,"Octa Core (4P + 4E), 12 Threads",16GB,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,one
23,24,24,HP,15s-fq2510tu Laptop,49580,64.000000,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",16GB,512GB,SSD,Intel Iris Xe Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
25,26,26,HP,15s-eq2132AU Laptop,43990,63.000000,5th Gen AMD Ryzen 5 5500U,"Hexa Core, 12 Threads",16GB,512GB,SSD,AMD Radeon AMD,15.6,1920.0,1080.0,Windows 11 OS,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
865,903,992,HP,Victus 15-fb0137AX Gaming Laptop,74990,67.000000,5th Gen AMD Ryzen 7 5800H,"Octa Core, 16 Threads",16GB,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,one
867,905,994,HP,ProBook 445 G8 7K2J8PA Business Laptop,46490,63.000000,5th Gen AMD Ryzen 7 5800U,"Octa Core, 16 Threads",8GB,512GB,SSD,AMD Radeon,14.0,1920.0,1080.0,DOS OS,one
872,910,999,HP,Victus 15-fb0131AX Gaming Laptop,51990,65.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,512GB,SSD,4GB AMD Radeon RX 5600M,15.6,1920.0,1080.0,Windows 11 OS,one
876,914,1003,HP,15s-fq3071TU Laptop,28490,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,512GB,SSD,Intel Integrated UHD Graphics,15.0,1366.0,768.0,Windows 11 OS,one
880,918,1007,HP,Victus 15-fb0135AX Gaming Laptop,59990,64.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,512GB,SSD,4GB NVIDIA GeForce RTX 3050,15.6,1920.0,1080.0,Windows 11 OS,one

In [266]:
hp_brand['warranty'].unique()

<StringArray>
['one', 'three', 'zero']
Length: 3, dtype: str

In [267]:
hp1=hp_brand[hp_brand['warranty']=='three']
hp1

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
481,503,570,HP,EliteBook 840 G6,90464,69.323529,8th Gen Intel Core i5 8265U,"Quad Core, 8 Threads",8GB,512GB,SSD,Integrated UHD Graphics 620,14.0,1920.0,1080.0,Windows 10 OS,three

In [268]:
hp_os=hp_brand[hp_brand['display_size']<=15]
hp_os

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
103,105,108,HP,14s-fq1092au Laptop,41950,64.000000,5th Gen AMD Ryzen 5 5500U,"Hexa Core, 12 Threads",8GB,512GB,SSD,AMD Radeon AMD,14.0,1920.0,1080.0,Windows 11 OS,one
138,142,156,HP,Pavilion x360 14-ek1010TU Laptop,79990,70.000000,13th Gen Intel Core i5 1335U,"10 Cores (2P + 8E), 12 Threads",16GB,1TB,SSD,Intel Integrated Iris Xe,14.0,1920.0,1080.0,Windows 11 OS,one
187,193,216,HP,Pavilion x360 14-ek1010TU Laptop,77889,70.000000,13th Gen Intel Core i5 1335U,"10 Cores (2P + 8E), 12 Threads",16GB,1TB,SSD,Intel Integrated Iris Xe,14.0,1920.0,1080.0,Windows 11 OS,one
243,256,289,HP,Pavilion 14-dv2153TU Laptop,69990,67.000000,12th Gen Intel Core i5 1235U,"10 Cores (2P + 8E), 12 Threads",16GB,1TB,SSD,Intel Integrated Iris Xe,14.0,1920.0,1080.0,Windows 11 OS,one
295,314,353,HP,Pavilion Plus ‎14-eh1047TU Laptop,107763,71.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,512GB,SSD,Intel Integrated Iris Xe,14.0,2880.0,1800.0,Windows 11 OS,one
297,316,355,HP,Pavilion Plus 14-eh1022TU Laptop,80490,69.000000,13th Gen Intel Core i5 1340P,"12 Cores (4P + 8E), 16 Threads",16GB,512GB,SSD,Intel Iris Xe Graphics,14.0,2240.0,1400.0,Windows 11 OS,one
302,321,360,HP,14-hr0000AU Laptop,48999,60.000000,7th Gen AMD Ryzen 5 7520U,"Quad Core, 8 Threads",16GB,512GB,SSD,AMD Radeon AMD,14.0,1920.0,1080.0,Windows 11 OS,one
374,394,435,HP,14s-dq2649TU Laptop,34999,60.000000,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,512GB,SSD,Intel Integrated UHD,14.0,1920.0,1080.0,Windows 11 OS,one
377,397,438,HP,Pavilion Plus 14-eh0037TU Laptop,82799,70.000000,12th Gen Intel Core i5 12500H,"12 Cores (4P + 8E), 16 Threads",16GB,512GB,SSD,Intel Integrated Iris Xe,14.0,2880.0,1800.0,Windows 11 OS,one
400,420,472,HP,Pavilion Aero 13-be2047AU Laptop,77990,69.000000,7th Gen AMD Ryzen 7 7735U,"Octa Core, 16 Threads",16GB,1TB,SSD,AMD Radeon AMD,13.3,1920.0,1200.0,Windows 11 OS,one
411,431,491,HP,Pavilion Plus 14-eh0037TU Laptop,83249,70.000000,12th Gen Intel Core i5 12500H,"12 Cores (4P + 8E), 16 Threads",16GB,512GB,SSD,Intel Integrated Iris Xe,14.0,2880.0,1800.0,Windows 11 OS,one
413,433,496,HP,Envy x360 13-bf0121TU Laptop,85490,71.000000,12th Gen Intel Core i5 1230U,"10 Cores, 12 Threads",16GB,512GB,SSD,Intel Integrated Iris Xe,13.4,1920.0,1200.0,Windows 11 OS,one
417,437,500,HP,Pavilion 14-dv2014TU Laptop,66648,64.000000,12th Gen Intel Core i5 1235U,"10 Cores (2P + 8E), 12 Threads",16GB,512GB,SSD,Intel Integrated UHD Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
447,468,532,HP,Pavilion 14s- fy1003AU Laptop,45890,69.323529,5th Gen AMD Ryzen 5 5500U,"Hexa Core, 12 Threads",16GB,512GB,SSD,AMD Radeon Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
455,476,540,HP,Pavilion 14-dv2041TU Laptop,67990,61.000000,12th Gen Intel Core i5 1235U,"10 Cores (2P + 8E), 12 Threads",16GB,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
458,479,543,HP,Pavilion 14-dv2015TU Laptop,83149,64.000000,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16GB,1TB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
463,484,548,HP,Pavilion 14-ec1003AU Laptop,51573,69.323529,5th Gen AMD Ryzen 5 5625U,"Hexa Core, 12 Threads",8GB,512GB,SSD,AMD Radeon Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
481,503,570,HP,EliteBook 840 G6,90464,69.323529,8th Gen Intel Core i5 8265U,"Quad Core, 8 Threads",8GB,512GB,SSD,Integrated UHD Graphics 620,14.0,1920.0,1080.0,Windows 10 OS,three
496,520,588,HP,Pavilion 14-EC1019AU Laptop,55990,69.323529,5th Gen AMD Ryzen 5 5625U,"Hexa Core, 12 Threads",16GB,512GB,SSD,AMD Radeon AMD,14.0,1920.0,1080.0,Windows 11 OS,one
550,574,654,HP,Pavilion Plus ‎14-ey0789AU Laptop,99999,70.000000,7th Gen Amd Ryzen 7 7840H,"Octa Core, 16 Threads",16GB,1TB,SSD,AMD Radeon 780M Graphics,14.0,2880.0,1800.0,Windows 11 OS,one
567,592,672,HP,14s-dr3002TU Laptop,26990,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,512GB,SSD,Intel UHD Graphics,14.0,1366.0,768.0,Windows 11 OS,one
574,599,679,HP,Zbook FireFly 14 G8 4F0W6PA Laptop,89999,70.000000,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",16GB,512GB,SSD,Intel UHD Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
600,627,708,HP,Pavilion x360 14-ek1021TU Laptop,91590,70.000000,13th Gen Intel Core i7 1355U,"10 Cores (2P + 8E), 12 Threads",16GB,512GB,SSD,Intel Integrated Iris Xe,14.0,1920.0,1080.0,Windows 11 OS,one
629,661,743,HP,240 G9 ALC 7M658PA Laptop,64800,69.323529,12th Gen Intel Core i5 1235U,"10 Cores (2P + 8E), 12 Threads",8GB,512GB,SSD,Intel Integrated,14.0,1366.0,768.0,DOS OS,one
687,720,803,HP,Envy x360 13-bf0141tu Laptop,107190,67.000000,12th Gen Intel Core i7 1250U,"10 Cores (2P + 8E), 12 Threads",16GB,512GB,SSD,Intel Integrated Iris Xe,13.3,2880.0,1800.0,Windows 11 OS,one
690,724,807,HP,Dragonfly G4 Laptop,231746,71.000000,13th Gen Intel Core i7 1365U,"10 Cores (2P + 8E), 12 Threads",16GB,512GB,SSD,Intel Iris Xe Graphics,13.5,1920.0,1280.0,Windows 11 OS,one
694,728,812,HP,Pavilion x360 14-ek1074TU Laptop,77990,67.000000,13th Gen Intel Core i5 1335U,"10 Cores (2P + 8E), 12 Threads",16GB,512GB,SSD,Intel Integrated Iris Xe,14.0,1920.0,1080.0,Windows 11 OS,one
768,806,891,HP,14-em0027AU Laptop,51990,60.000000,7th Gen AMD Ryzen 5 7520U,"Quad Core, 8 Threads",16GB,512GB,SSD,AMD Radeon AMD,14.0,1920.0,1080.0,Windows 11 OS,one
770,808,893,HP,14-em0025AU Laptop,34990,69.323529,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",8GB,512GB,SSD,AMD Radeon AMD,14.0,1920.0,1080.0,Windows 11 OS,one
776,814,899,HP,14-gr0000TU Laptop,44990,69.323529,13th Gen Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,512GB,SSD,Intel UHD Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
778,816,901,HP,14-hr0000AU Laptop,50990,60.000000,7th Gen AMD Ryzen 5 7520U,"Quad Core, 8 Threads",16GB,512GB,SSD,AMD Radeon AMD,14.0,1920.0,1080.0,Windows 11 OS,one
790,828,913,HP,14-em0026AU Laptop,46990,69.323529,7th Gen AMD Ryzen 5 7520U,"Quad Core, 8 Threads",8GB,512GB,SSD,AMD Radeon AMD,14.0,1920.0,1080.0,Windows 11 OS,one
803,841,927,HP,Pavilion 14-dv1043TU Laptop,58990,62.000000,11th Gen Intel Core i5 1155G7,"Quad Core, 8 Threads",8GB,512GB,SSD,Intel Integrated Iris Xe,14.0,1920.0,1080.0,Windows 11 OS,one
858,896,984,HP,14s-dr3003TU 832T7PA Laptop,29999,69.323529,Intel Pentium Silver N6000,"Quad Core, 4 Threads",8GB,512GB,SSD,Intel UHD Graphics,14.0,1366.0,768.0,Windows 11 OS,one
867,905,994,HP,ProBook 445 G8 7K2J8PA Business Laptop,46490,63.000000,5th Gen AMD Ryzen 7 5800U,"Octa Core, 16 Threads",8GB,512GB,SSD,AMD Radeon,14.0,1920.0,1080.0,DOS OS,one
876,914,1003,HP,15s-fq3071TU Laptop,28490,69.323529,Intel Celeron N4500,"Dual Core, 2 Threads",8GB,512GB,SSD,Intel Integrated UHD Graphics,15.0,1366.0,768.0,Windows 11 OS,one

In [269]:
apple_brand=df[df['brand']=='Apple']
apple_brand

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
21,22,22,Apple,MacBook Air 2022 Laptop,104990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,256GB,SSD,8-Core GPU,13.6,2560.0,1664.0,Mac OS,one
95,97,100,Apple,MacBook Air 15 2023 Laptop,126990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,256GB,SSD,10-Core GPU,15.3,2880.0,1864.0,Mac OS,one
158,164,185,Apple,MacBook Air 15 2023 Laptop,144990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,512GB,SSD,10-Core GPU,15.3,2880.0,1864.0,Mac OS,one
206,213,241,Apple,MacBook Air 2022 Laptop,135990,69.323529,Apple M2 Apple M2 Chip,Octa Core,8GB,512GB,SSD,10-Core GPU,13.6,2560.0,1664.0,Mac OS,one
213,221,250,Apple,MacBook Air 2020 MGN73HN Laptop,112990,69.323529,Apple M1 Apple M1 Chip,Octa Core (4P + 4E),8GB,512GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
215,224,253,Apple,MacBook Pro 16 Laptop,201498,81.000000,9th Gen Intel Core i9,Octa Core,32GB,2TB,SSD,4GB Radeon Pro 5500M,16.0,3072.0,1920.0,Mac Catalina OS,one
375,395,436,Apple,MacBook Pro 14 inch Laptop,290990,61.000000,Apple M2 Max M2 Max,12 Cores,32GB,1TB,SSD,30-core GPU,14.2,3024.0,1964.0,Mac OS,one
376,396,437,Apple,MacBook Pro 14 inch Laptop,234990,69.323529,Apple M2 Pro M2 Pro,12 Cores,16GB,1TB,SSD,19-core GPU,14.2,3024.0,1964.0,Mac OS,one
468,489,555,Apple,MacBook Pro 14 inch MKGQ3HN Laptop,239900,69.323529,Apple M1 Pro M1 Pro,10 Cores (8P + 2E),16GB,1TB,SSD,16-core GPU,14.2,3024.0,1964.0,Mac OS,one
469,490,556,Apple,MacBook Pro 16 inch MK1A3HN Laptop,309490,60.000000,Apple M1 Max M1 Max,10 Cores,32GB,1TB,SSD,32-core GPU,16.2,3456.0,2234.0,Mac OS,one
483,505,572,Apple,MacBook Pro 2018 13-inch Touch Bar Laptop,199900,69.323529,Intel,Quad Core,8GB,512GB,SSD,Intel Iris Plus Graphics 655,13.3,1600.0,2560.0,Mac High Sierra OS,one
504,528,599,Apple,MacBook Pro 16 inch MK183HN Laptop,215994,69.323529,Apple M1 Pro M1 Pro,10 Cores,16GB,512GB,SSD,16-core GPU,16.2,3456.0,2234.0,Mac OS,one
505,529,600,Apple,MacBook Pro 14 inch MKGQ3HN Laptop,215994,69.323529,Apple M1 Pro M1 Pro,10 Cores (8P + 2E),16GB,1TB,SSD,16-core GPU,14.2,3024.0,1964.0,Mac OS,one
513,537,611,Apple,MacBook Air 2020 Laptop,72999,69.323529,10th Gen Intel Core i3,"Quad Core, 8 Threads",8GB,256GB,SSD,Intel Iris Plus,13.3,2560.0,1600.0,Mac 10.15.3\t OS,zero
514,538,612,Apple,MacBook Air 2020 Laptop,109999,69.323529,10th Gen Intel Core i7,"Quad Core, 8 Threads",8GB,512GB,SSD,Intel Iris Plus,13.3,2560.0,1600.0,Mac 10.15.3\t OS,zero

In [270]:
apple_brand1=apple_brand[apple_brand['warranty']=='three']
apple_brand1

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, brand, name, price, spec_rating, processor, CPU, Ram, ROM, ROM_type, GPU, display_size, resolution_width, resolution_height, OS, warranty]
Index: []

In [271]:
apple_brand2=apple_brand[apple_brand['display_size']<=14]
apple_brand2

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
21,22,22,Apple,MacBook Air 2022 Laptop,104990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,256GB,SSD,8-Core GPU,13.6,2560.0,1664.0,Mac OS,one
206,213,241,Apple,MacBook Air 2022 Laptop,135990,69.323529,Apple M2 Apple M2 Chip,Octa Core,8GB,512GB,SSD,10-Core GPU,13.6,2560.0,1664.0,Mac OS,one
213,221,250,Apple,MacBook Air 2020 MGN73HN Laptop,112990,69.323529,Apple M1 Apple M1 Chip,Octa Core (4P + 4E),8GB,512GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
483,505,572,Apple,MacBook Pro 2018 13-inch Touch Bar Laptop,199900,69.323529,Intel,Quad Core,8GB,512GB,SSD,Intel Iris Plus Graphics 655,13.3,1600.0,2560.0,Mac High Sierra OS,one
513,537,611,Apple,MacBook Air 2020 Laptop,72999,69.323529,10th Gen Intel Core i3,"Quad Core, 8 Threads",8GB,256GB,SSD,Intel Iris Plus,13.3,2560.0,1600.0,Mac 10.15.3\t OS,zero
514,538,612,Apple,MacBook Air 2020 Laptop,109999,69.323529,10th Gen Intel Core i7,"Quad Core, 8 Threads",8GB,512GB,SSD,Intel Iris Plus,13.3,2560.0,1600.0,Mac 10.15.3\t OS,zero

In [272]:
apple_brand3=apple_brand[apple_brand['price']>=50000]
apple_brand3

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
21,22,22,Apple,MacBook Air 2022 Laptop,104990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,256GB,SSD,8-Core GPU,13.6,2560.0,1664.0,Mac OS,one
95,97,100,Apple,MacBook Air 15 2023 Laptop,126990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,256GB,SSD,10-Core GPU,15.3,2880.0,1864.0,Mac OS,one
158,164,185,Apple,MacBook Air 15 2023 Laptop,144990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,512GB,SSD,10-Core GPU,15.3,2880.0,1864.0,Mac OS,one
206,213,241,Apple,MacBook Air 2022 Laptop,135990,69.323529,Apple M2 Apple M2 Chip,Octa Core,8GB,512GB,SSD,10-Core GPU,13.6,2560.0,1664.0,Mac OS,one
213,221,250,Apple,MacBook Air 2020 MGN73HN Laptop,112990,69.323529,Apple M1 Apple M1 Chip,Octa Core (4P + 4E),8GB,512GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
215,224,253,Apple,MacBook Pro 16 Laptop,201498,81.000000,9th Gen Intel Core i9,Octa Core,32GB,2TB,SSD,4GB Radeon Pro 5500M,16.0,3072.0,1920.0,Mac Catalina OS,one
375,395,436,Apple,MacBook Pro 14 inch Laptop,290990,61.000000,Apple M2 Max M2 Max,12 Cores,32GB,1TB,SSD,30-core GPU,14.2,3024.0,1964.0,Mac OS,one
376,396,437,Apple,MacBook Pro 14 inch Laptop,234990,69.323529,Apple M2 Pro M2 Pro,12 Cores,16GB,1TB,SSD,19-core GPU,14.2,3024.0,1964.0,Mac OS,one
468,489,555,Apple,MacBook Pro 14 inch MKGQ3HN Laptop,239900,69.323529,Apple M1 Pro M1 Pro,10 Cores (8P + 2E),16GB,1TB,SSD,16-core GPU,14.2,3024.0,1964.0,Mac OS,one
469,490,556,Apple,MacBook Pro 16 inch MK1A3HN Laptop,309490,60.000000,Apple M1 Max M1 Max,10 Cores,32GB,1TB,SSD,32-core GPU,16.2,3456.0,2234.0,Mac OS,one
483,505,572,Apple,MacBook Pro 2018 13-inch Touch Bar Laptop,199900,69.323529,Intel,Quad Core,8GB,512GB,SSD,Intel Iris Plus Graphics 655,13.3,1600.0,2560.0,Mac High Sierra OS,one
504,528,599,Apple,MacBook Pro 16 inch MK183HN Laptop,215994,69.323529,Apple M1 Pro M1 Pro,10 Cores,16GB,512GB,SSD,16-core GPU,16.2,3456.0,2234.0,Mac OS,one
505,529,600,Apple,MacBook Pro 14 inch MKGQ3HN Laptop,215994,69.323529,Apple M1 Pro M1 Pro,10 Cores (8P + 2E),16GB,1TB,SSD,16-core GPU,14.2,3024.0,1964.0,Mac OS,one
513,537,611,Apple,MacBook Air 2020 Laptop,72999,69.323529,10th Gen Intel Core i3,"Quad Core, 8 Threads",8GB,256GB,SSD,Intel Iris Plus,13.3,2560.0,1600.0,Mac 10.15.3\t OS,zero
514,538,612,Apple,MacBook Air 2020 Laptop,109999,69.323529,10th Gen Intel Core i7,"Quad Core, 8 Threads",8GB,512GB,SSD,Intel Iris Plus,13.3,2560.0,1600.0,Mac 10.15.3\t OS,zero

In [273]:
df[(df['brand']=='Apple')&(df['price']>=50000) & (df['warranty']<='one')]

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
21,22,22,Apple,MacBook Air 2022 Laptop,104990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,256GB,SSD,8-Core GPU,13.6,2560.0,1664.0,Mac OS,one
95,97,100,Apple,MacBook Air 15 2023 Laptop,126990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,256GB,SSD,10-Core GPU,15.3,2880.0,1864.0,Mac OS,one
158,164,185,Apple,MacBook Air 15 2023 Laptop,144990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,512GB,SSD,10-Core GPU,15.3,2880.0,1864.0,Mac OS,one
206,213,241,Apple,MacBook Air 2022 Laptop,135990,69.323529,Apple M2 Apple M2 Chip,Octa Core,8GB,512GB,SSD,10-Core GPU,13.6,2560.0,1664.0,Mac OS,one
213,221,250,Apple,MacBook Air 2020 MGN73HN Laptop,112990,69.323529,Apple M1 Apple M1 Chip,Octa Core (4P + 4E),8GB,512GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
215,224,253,Apple,MacBook Pro 16 Laptop,201498,81.000000,9th Gen Intel Core i9,Octa Core,32GB,2TB,SSD,4GB Radeon Pro 5500M,16.0,3072.0,1920.0,Mac Catalina OS,one
375,395,436,Apple,MacBook Pro 14 inch Laptop,290990,61.000000,Apple M2 Max M2 Max,12 Cores,32GB,1TB,SSD,30-core GPU,14.2,3024.0,1964.0,Mac OS,one
376,396,437,Apple,MacBook Pro 14 inch Laptop,234990,69.323529,Apple M2 Pro M2 Pro,12 Cores,16GB,1TB,SSD,19-core GPU,14.2,3024.0,1964.0,Mac OS,one
468,489,555,Apple,MacBook Pro 14 inch MKGQ3HN Laptop,239900,69.323529,Apple M1 Pro M1 Pro,10 Cores (8P + 2E),16GB,1TB,SSD,16-core GPU,14.2,3024.0,1964.0,Mac OS,one
469,490,556,Apple,MacBook Pro 16 inch MK1A3HN Laptop,309490,60.000000,Apple M1 Max M1 Max,10 Cores,32GB,1TB,SSD,32-core GPU,16.2,3456.0,2234.0,Mac OS,one
483,505,572,Apple,MacBook Pro 2018 13-inch Touch Bar Laptop,199900,69.323529,Intel,Quad Core,8GB,512GB,SSD,Intel Iris Plus Graphics 655,13.3,1600.0,2560.0,Mac High Sierra OS,one
504,528,599,Apple,MacBook Pro 16 inch MK183HN Laptop,215994,69.323529,Apple M1 Pro M1 Pro,10 Cores,16GB,512GB,SSD,16-core GPU,16.2,3456.0,2234.0,Mac OS,one
505,529,600,Apple,MacBook Pro 14 inch MKGQ3HN Laptop,215994,69.323529,Apple M1 Pro M1 Pro,10 Cores (8P + 2E),16GB,1TB,SSD,16-core GPU,14.2,3024.0,1964.0,Mac OS,one

In [276]:
df.query("brand =='Apple' and warranty=='one'")

,Unnamed: 0.1,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
21,22,22,Apple,MacBook Air 2022 Laptop,104990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,256GB,SSD,8-Core GPU,13.6,2560.0,1664.0,Mac OS,one
95,97,100,Apple,MacBook Air 15 2023 Laptop,126990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,256GB,SSD,10-Core GPU,15.3,2880.0,1864.0,Mac OS,one
158,164,185,Apple,MacBook Air 15 2023 Laptop,144990,69.323529,Apple M2,Octa Core (4P + 4E),8GB,512GB,SSD,10-Core GPU,15.3,2880.0,1864.0,Mac OS,one
206,213,241,Apple,MacBook Air 2022 Laptop,135990,69.323529,Apple M2 Apple M2 Chip,Octa Core,8GB,512GB,SSD,10-Core GPU,13.6,2560.0,1664.0,Mac OS,one
213,221,250,Apple,MacBook Air 2020 MGN73HN Laptop,112990,69.323529,Apple M1 Apple M1 Chip,Octa Core (4P + 4E),8GB,512GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
215,224,253,Apple,MacBook Pro 16 Laptop,201498,81.000000,9th Gen Intel Core i9,Octa Core,32GB,2TB,SSD,4GB Radeon Pro 5500M,16.0,3072.0,1920.0,Mac Catalina OS,one
375,395,436,Apple,MacBook Pro 14 inch Laptop,290990,61.000000,Apple M2 Max M2 Max,12 Cores,32GB,1TB,SSD,30-core GPU,14.2,3024.0,1964.0,Mac OS,one
376,396,437,Apple,MacBook Pro 14 inch Laptop,234990,69.323529,Apple M2 Pro M2 Pro,12 Cores,16GB,1TB,SSD,19-core GPU,14.2,3024.0,1964.0,Mac OS,one
468,489,555,Apple,MacBook Pro 14 inch MKGQ3HN Laptop,239900,69.323529,Apple M1 Pro M1 Pro,10 Cores (8P + 2E),16GB,1TB,SSD,16-core GPU,14.2,3024.0,1964.0,Mac OS,one
469,490,556,Apple,MacBook Pro 16 inch MK1A3HN Laptop,309490,60.000000,Apple M1 Max M1 Max,10 Cores,32GB,1TB,SSD,32-core GPU,16.2,3456.0,2234.0,Mac OS,one
483,505,572,Apple,MacBook Pro 2018 13-inch Touch Bar Laptop,199900,69.323529,Intel,Quad Core,8GB,512GB,SSD,Intel Iris Plus Graphics 655,13.3,1600.0,2560.0,Mac High Sierra OS,one
504,528,599,Apple,MacBook Pro 16 inch MK183HN Laptop,215994,69.323529,Apple M1 Pro M1 Pro,10 Cores,16GB,512GB,SSD,16-core GPU,16.2,3456.0,2234.0,Mac OS,one
505,529,600,Apple,MacBook Pro 14 inch MKGQ3HN Laptop,215994,69.323529,Apple M1 Pro M1 Pro,10 Cores (8P + 2E),16GB,1TB,SSD,16-core GPU,14.2,3024.0,1964.0,Mac OS,one

In [277]:
x=df.drop('price',axis=1)
x

,Unnamed: 0.1,Unnamed: 0,brand,name,spec_rating,processor,CPU,Ram,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,0,HP,Victus 15-fb0157AX Gaming Laptop,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,one
1,1,1,HP,15s-fq5007TU Laptop,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
2,2,2,Acer,One 14 Z8-415 Laptop,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,one
3,3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,one
4,4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69.323529,Apple M1,Octa Core (4P + 4E),8GB,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,926,1015,Asus,Vivobook 15X 2023 K3504VAB-NJ321WS Laptop,69.323529,13th Gen ‎Intel Core i3 1315U,"Hexa Core (2P + 4E), 8 Threads",8GB,512GB,SSD,Integrated Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,one
889,927,1016,Asus,TUF A15 FA577RM-HQ032WS Laptop,71.000000,6th Gen AMD Ryzen 7 6800H,"Octa Core, 16 Threads",16GB,1TB,SSD,6GB NVIDIA GeForce RTX 3060,15.6,2560.0,1440.0,Windows 11 OS,one
890,928,1017,Asus,ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...,89.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",32GB,1TB,SSD,8GB NVIDIA GeForce RTX 4060,14.0,2560.0,1600.0,Windows 11 OS,one
891,929,1018,Asus,TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop,73.000000,13th Gen Intel Core i7 13700H,"14 Cores (6P + 8E), 20 Threads",16GB,512GB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one
892,930,1019,Asus,TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop,84.000000,7th Gen AMD Ryzen 9 7940HS,"Octa Core, 16 Threads",16GB,1TB,SSD,6GB NVIDIA GeForce RTX 4050,15.6,1920.0,1080.0,Windows 11 OS,one

In [278]:
y=df[['price']]
y

      price
0     49900
1     39900
2     26990
3     59729
4     69990
..      ...
888   44990
889  110000
890  189990
891  129990
892  131990

[893 rows x 1 columns]

In [289]:
mx=df.drop('price',axis=1)
y=df[['price']]
y=x
print(y)

     Unnamed: 0.1  Unnamed: 0   brand  \
0               0           0      HP
1               1           1      HP
2               2           2    Acer
3               3           3  Lenovo
4               4           4   Apple
..            ...         ...     ...
888           926        1015    Asus
889           927        1016    Asus
890           928        1017    Asus
891           929        1018    Asus
892           930        1019    Asus

                                                  name  spec_rating  \
0                     Victus 15-fb0157AX Gaming Laptop    73.000000
1                                  15s-fq5007TU Laptop    60.000000
2                                 One 14 Z8-415 Laptop    69.323529
3                 Yoga Slim 6 14IAP8 82WU0095IN Laptop    66.000000
4                      MacBook Air 2020 MGND3HN Laptop    69.323529
..                                                 ...          ...
888          Vivobook 15X 2023 K3504VAB-NJ321WS Laptop    69.323529
889                     TUF A15 FA577RM-HQ032WS Laptop    71.000000
890  ROG Zephyrus G14 2023 GA402XV-N2034WS Gaming L...    89.000000
891  TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop    73.000000
892  TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop    84.000000

                         processor                             CPU   Ram  \
0        5th Gen AMD Ryzen 5 5600H           Hexa Core, 12 Threads   8GB
1     12th Gen Intel Core i3 1215U  Hexa Core (2P + 4E), 8 Threads   8GB
2    11th Gen Intel Core i3 1115G4            Dual Core, 4 Threads   8GB
3     12th Gen Intel Core i5 1240P  12 Cores (4P + 8E), 16 Threads  16GB
4                         Apple M1             Octa Core (4P + 4E)   8GB
..                             ...                             ...   ...
888  13th Gen ‎Intel Core i3 1315U  Hexa Core (2P + 4E), 8 Threads   8GB
889      6th Gen AMD Ryzen 7 6800H           Octa Core, 16 Threads  16GB
890     7th Gen AMD Ryzen 9 7940HS           Octa Core, 16 Threads  32GB
891  13th Gen Intel Core i7 13700H  14 Cores (6P + 8E), 20 Threads  16GB
892     7th Gen AMD Ryzen 9 7940HS           Octa Core, 16 Threads  16GB

       ROM ROM_type                            GPU  display_size  \
0    512GB      SSD        4GB AMD Radeon RX 6500M          15.6
1    512GB      SSD             Intel UHD Graphics          15.6
2    512GB      SSD         Intel Iris Xe Graphics          14.0
3    512GB      SSD       Intel Integrated Iris Xe          14.0
4    256GB      SSD   Apple M1 Integrated Graphics          13.3
..     ...      ...                            ...           ...
888  512GB      SSD  Integrated Intel UHD Graphics          15.6
889    1TB      SSD    6GB NVIDIA GeForce RTX 3060          15.6
890    1TB      SSD    8GB NVIDIA GeForce RTX 4060          14.0
891  512GB      SSD    6GB NVIDIA GeForce RTX 4050          15.6
892    1TB      SSD    6GB NVIDIA GeForce RTX 4050          15.6

     resolution_width  resolution_height              OS warranty
0              1920.0             1080.0   Windows 11 OS      one
1              1920.0             1080.0   Windows 11 OS      one
2              1920.0             1080.0   Windows 11 OS      one
3              2240.0             1400.0   Windows 11 OS      one
4              2560.0             1600.0          Mac OS      one
..                ...                ...             ...      ...
888            1920.0             1080.0   Windows 11 OS      one
889            2560.0             1440.0  Windows 11  OS      one
890            2560.0             1600.0   Windows 11 OS      one
891            1920.0             1080.0   Windows 11 OS      one
892            1920.0             1080.0   Windows 11 OS      one

[893 rows x 16 columns]

In [ ]:
####y=mx+c linear regression