In [87]:
pip install pandas

Requirement already satisfied: pandas in c:\users\win-11\desktop\data science\datascience\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\win-11\desktop\data science\datascience\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\win-11\desktop\data science\datascience\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\win-11\desktop\data science\datascience\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\win-11\desktop\data science\datascience\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 26.1.1
[notice] To update, run: c:\Users\win-11\Desktop\data science\datascience\Scripts\python.exe -m pip install --upgrade pip

pandas is a powerful open-source Python library designed for data manipulation, analysis, and processing. It provides easy-to-use data structures and tools that help users work efficiently with structured data such as tables, spreadsheets, databases, and CSV files.

The name “pandas” comes from Panel Data, a term used in statistics and economics for multidimensional structured datasets.

Main Purpose of pandas

Pandas is mainly used to:

Organize data
Clean and preprocess data
Analyze information
Transform datasets
Handle missing or inconsistent values
Perform statistical analysis
Prepare data for visualization or machine learning

It simplifies complex data operations that would otherwise require large amounts of code.

Key Features of pandas
1. Fast and Efficient Data Handling

Pandas is optimized for high-performance operations on structured data. It can process large datasets quickly and efficiently.

2. Easy Data Cleaning

Real-world data is often incomplete or messy. Pandas provides tools to:

Remove duplicates
Handle missing values
Rename columns
Convert data types
Format inconsistent data
3. Powerful Data Analysis

Pandas allows users to:

Filter records
Sort data
Group similar values
Calculate statistics
Merge datasets
Analyze trends and patterns
4. Flexible Data Input and Output

Pandas can read and write data from multiple formats:

CSV
Excel
JSON
SQL databases
HTML tables

This makes it useful for many real-world applications.

Core Data Structures in pandas
Series

A Series is a one-dimensional labeled data structure similar to a single column in a spreadsheet.

Characteristics:

Stores one type of data
Has labels called indexes
Supports mathematical operations
DataFrame

A DataFrame is a two-dimensional table consisting of rows and columns.

Characteristics:

Similar to an Excel sheet or database table
Each column can store different data types
Supports indexing, filtering, grouping, and aggregation

The DataFrame is the most important and commonly used structure in pandas.

Important Concepts in pandas
Indexing

Each row and column in pandas has labels that help access data efficiently.

Filtering

Users can select specific rows or columns based on conditions.

Example idea:

Selecting employees with salary greater than a certain amount
Grouping

Data can be grouped based on categories for summary analysis.

Example idea:

Calculating average salary department-wise
Aggregation

Pandas can compute:

Sum
Mean
Count
Maximum
Minimum
Standard deviation
Handling Missing Data

Pandas provides methods to:

Detect missing values
Replace missing values
Remove incomplete records

This is very important in data science workflows.

Advantages of pandas
Simple and readable syntax
Saves time in data processing
Excellent for exploratory data analysis
Strong integration with other Python libraries
Widely used in industry and research
Large community support
Applications of pandas

Pandas is used in:

Data science
Machine learning
Finance
Business analytics
Scientific research
Artificial intelligence
Web analytics
Stock market analysis
pandas in the Data Science Workflow

Typical workflow:

Collect data
Load data using pandas
Clean and preprocess data
Analyze and transform data
Visualize or model the data

Pandas acts as the foundation for most Python-based data analysis tasks.

Difference Between pandas and NumPy
NumPy	pandas
Works mainly with numerical arrays	Works with structured/tabular data
Faster for pure mathematical operations	Better for real-world data analysis
Limited labeling features	Provides labeled rows and columns
Focused on numerical computing	Focused on data manipulation
Why pandas is Popular

Pandas became popular because it:

Reduces coding complexity
Handles real-world data efficiently
Offers spreadsheet-like operations in Python
Makes analysis easier for beginners and professionals

It is considered one of the most essential libraries in the Python ecosystem.

In [88]:
import os
import numpy as np
import pandas as pd

In [89]:
df=pd.read_csv(r"C:\Users\win-11\Desktop\data science\pandas\Used_Bikes.csv")

In [90]:
df ##fd stands for data frame

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [91]:
df.head()## it bydefault gives 5 rows

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [92]:
df.head(10) ###we can add hoe many rows we want

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [93]:
df.tail() ##last 5 rows by default

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [94]:
df.tail(10) ##can add how many last rows we want

,bike_name,price,city,kms_driven,owner,age,power,brand
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [95]:
df.info()## gives info of dataset

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [96]:
df.columns##gives column from dataset

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [97]:
df["price"] ###for any specific column

0         35000.0
1        119900.0
2        600000.0
3         65000.0
4         80000.0
           ...
32643     39000.0
32644     30000.0
32645     60000.0
32646     15600.0
32647     22000.0
Name: price, Length: 32648, dtype: float64

In [98]:
df[["price"]] ##for extract data into format we use double[[]]

          price
0       35000.0
1      119900.0
2      600000.0
3       65000.0
4       80000.0
...         ...
32643   39000.0
32644   30000.0
32645   60000.0
32646   15600.0
32647   22000.0

[32648 rows x 1 columns]

In [99]:
df[["price","brand"]] ##for extracting multiple columns, can be done simply by adding column name with commas in bracket

          price          brand
0       35000.0            TVS
1      119900.0  Royal Enfield
2      600000.0        Triumph
3       65000.0            TVS
4       80000.0         Yamaha
...         ...            ...
32643   39000.0           Hero
32644   30000.0            TVS
32645   60000.0          Bajaj
32646   15600.0           Hero
32647   22000.0          Bajaj

[32648 rows x 2 columns]

In [100]:
df["brand"].unique() ##for unique name of brands

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [101]:
df["owner"].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [102]:
df["brand"].nunique() ##for counting number of unique brands

23

In [103]:
df["brand"].value_counts() ##for counting no. of items in each brand

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [104]:
df.duplicated().sum()

np.int64(25324)

In [105]:
df.drop_duplicates() ##to drop duplicates values ##temporaryaily dropped

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [106]:
df.duplicated().sum() ##to check duplicte vlues are droppped temporary

np.int64(25324)

In [107]:
df.drop_duplicates(inplace=True) ##for permanently deleteing duplicates values

In [108]:
df.duplicated().sum() ##for checking whether it is deleted or not

np.int64(0)

In [109]:
df.isnull() ##to check null values

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [110]:
df.isnull().sum() ##to get sum of null values

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [111]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [112]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [113]:
owner_dict={'First Owner':1,'Second Owner':2,'Third Ownner':3,'Fourth Owner Or More':4}

In [114]:
df['owner']=df['owner'].map(owner_dict)

In [115]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1.0,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1.0,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,1.0,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1.0,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,1.0,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,1.0,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,1.0,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,1.0,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,1.0,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,1.0,5.0,220.0,Bajaj

In [116]:
#df.info()

In [117]:
#df.drop('city',axis=1,inplace=True) ##to drop column 
#axis : 1 for column and 0 for row
#df

In [118]:
#f.drop(['price','bike_name'],axis=1,inplace=True) ##to drop multiple column from dataset

In [119]:
#df

In [120]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7240 non-null   float64
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(5), str(3)
memory usage: 515.0 KB

In [121]:
obj_val=df.select_dtypes(include='O')
obj_val

C:\Users\win-11\AppData\Local\Temp\ipykernel_26368\3533966632.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_val=df.select_dtypes(include='O')

                                 bike_name       city            brand
0       TVS Star City Plus Dual Tone 110cc  Ahmedabad              TVS
1              Royal Enfield Classic 350cc      Delhi    Royal Enfield
2                     Triumph Daytona 675R      Delhi          Triumph
3                     TVS Apache RTR 180cc  Bangalore              TVS
4     Yamaha FZ S V 2.0 150cc-Ltd. Edition  Bangalore           Yamaha
...                                    ...        ...              ...
9362             Hero Hunk Rear Disc 150cc      Delhi             Hero
9369                   Bajaj Avenger 220cc  Bangalore            Bajaj
9370        Harley-Davidson Street 750 ABS    Jodhpur  Harley-Davidson
9371                 Bajaj Dominar 400 ABS  Hyderabad            Bajaj
9372              Bajaj Avenger Street 220  Hyderabad            Bajaj

[7324 rows x 3 columns]

In [122]:
num_val=df.select_dtypes(exclude='O')

In [123]:
num_val

         price  kms_driven  owner  age  power
0      35000.0     17654.0    1.0  3.0  110.0
1     119900.0     11000.0    1.0  4.0  350.0
2     600000.0       110.0    1.0  8.0  675.0
3      65000.0     16329.0    1.0  4.0  180.0
4      80000.0     10000.0    1.0  3.0  150.0
...        ...         ...    ...  ...    ...
9362   25000.0     48587.0    1.0  8.0  150.0
9369   35000.0     60000.0    1.0  9.0  220.0
9370  450000.0      3430.0    1.0  4.0  750.0
9371  139000.0     21300.0    1.0  4.0  400.0
9372   80000.0      7127.0    1.0  5.0  220.0

[7324 rows x 5 columns]

In [124]:
complete_Data=pd.concat([obj_val,num_val],axis =1) ##for complete data

In [125]:
complete_Data

,bike_name,city,brand,price,kms_driven,owner,age,power
0,TVS Star City Plus Dual Tone 110cc,Ahmedabad,TVS,35000.0,17654.0,1.0,3.0,110.0
1,Royal Enfield Classic 350cc,Delhi,Royal Enfield,119900.0,11000.0,1.0,4.0,350.0
2,Triumph Daytona 675R,Delhi,Triumph,600000.0,110.0,1.0,8.0,675.0
3,TVS Apache RTR 180cc,Bangalore,TVS,65000.0,16329.0,1.0,4.0,180.0
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,Bangalore,Yamaha,80000.0,10000.0,1.0,3.0,150.0
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,Delhi,Hero,25000.0,48587.0,1.0,8.0,150.0
9369,Bajaj Avenger 220cc,Bangalore,Bajaj,35000.0,60000.0,1.0,9.0,220.0
9370,Harley-Davidson Street 750 ABS,Jodhpur,Harley-Davidson,450000.0,3430.0,1.0,4.0,750.0
9371,Bajaj Dominar 400 ABS,Hyderabad,Bajaj,139000.0,21300.0,1.0,4.0,400.0
9372,Bajaj Avenger Street 220,Hyderabad,Bajaj,80000.0,7127.0,1.0,5.0,220.0

In [126]:
#filtering
df[df['brand']=='TVS'] ##for info of specific data

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1.0,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1.0,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,1.0,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,1.0,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,1.0,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
9247,TVS Apache RTR 160cc Rear Disc,70000.0,Ghaziabad,4116.0,1.0,3.0,160.0,TVS
9307,TVS Apache RTR 160cc,30000.0,Alibag,30000.0,1.0,10.0,160.0,TVS
9312,TVS Apache RTR 200 4V FI,65450.0,Delhi,9238.0,1.0,3.0,200.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,1.0,14.0,150.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,1.0,2.0,110.0,TVS

#### task
* drop duplicate value
* drop null value
* drop uncessary colunm
* int into str

In [127]:
tvs_brand=df[df['brand']=='TVS']

In [128]:
tvs_brand['owner'].unique()

array([ 1.,  2., nan])

In [129]:
tvs_brand=tvs_brand[tvs_brand['owner']=='First Owner']

In [130]:
tvs_brand=df[df['brand']=='TVS']

In [131]:
tvs_brand

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,1.0,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,1.0,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,1.0,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,1.0,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,1.0,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
9247,TVS Apache RTR 160cc Rear Disc,70000.0,Ghaziabad,4116.0,1.0,3.0,160.0,TVS
9307,TVS Apache RTR 160cc,30000.0,Alibag,30000.0,1.0,10.0,160.0,TVS
9312,TVS Apache RTR 200 4V FI,65450.0,Delhi,9238.0,1.0,3.0,200.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,1.0,14.0,150.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,1.0,2.0,110.0,TVS

In [132]:
tvs_brand1=tvs_brand[tvs_brand["age"]<=2]

In [133]:
##all the bikes of royal enfied listed below
royal_enfield=df[df['brand']=='Royal Enfield']

In [134]:
royal_enfield

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1.0,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,1.0,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,2.0,7.0,500.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,1.0,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,1.0,5.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
9261,Royal Enfield Classic 500cc,146006.0,Guwahati,8575.0,1.0,4.0,500.0,Royal Enfield
9319,Royal Enfield Classic 350cc,100000.0,Chennai,25000.0,1.0,10.0,350.0,Royal Enfield
9337,Royal Enfield Himalayan 410cc,120000.0,Gurgaon,8492.0,1.0,5.0,410.0,Royal Enfield
9338,Royal Enfield Himalayan 410cc,138000.0,Delhi,5000.0,1.0,5.0,410.0,Royal Enfield
9344,Royal Enfield Bullet Twinspark 350cc,80000.0,Delhi,56968.0,1.0,8.0,350.0,Royal Enfield

In [135]:
##bike with owner less than orequals to 3
royal_enfield1=royal_enfield[royal_enfield['owner']<=3]

In [136]:
royal_enfield1

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1.0,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,1.0,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,2.0,7.0,500.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,1.0,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,1.0,5.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
9261,Royal Enfield Classic 500cc,146006.0,Guwahati,8575.0,1.0,4.0,500.0,Royal Enfield
9319,Royal Enfield Classic 350cc,100000.0,Chennai,25000.0,1.0,10.0,350.0,Royal Enfield
9337,Royal Enfield Himalayan 410cc,120000.0,Gurgaon,8492.0,1.0,5.0,410.0,Royal Enfield
9338,Royal Enfield Himalayan 410cc,138000.0,Delhi,5000.0,1.0,5.0,410.0,Royal Enfield
9344,Royal Enfield Bullet Twinspark 350cc,80000.0,Delhi,56968.0,1.0,8.0,350.0,Royal Enfield

In [137]:
##all the bikes of royal enfield with price less than equal to 200000
royal_enfield2=royal_enfield[royal_enfield['price']<=150000]

In [138]:
royal_enfield2

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1.0,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,1.0,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,2.0,7.0,500.0,Royal Enfield
23,Royal Enfield Classic Chrome 500cc,121700.0,Kalyan,24520.0,1.0,5.0,500.0,Royal Enfield
36,Royal Enfield Classic 350cc,98800.0,Kochi,39000.0,1.0,5.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
9261,Royal Enfield Classic 500cc,146006.0,Guwahati,8575.0,1.0,4.0,500.0,Royal Enfield
9319,Royal Enfield Classic 350cc,100000.0,Chennai,25000.0,1.0,10.0,350.0,Royal Enfield
9337,Royal Enfield Himalayan 410cc,120000.0,Gurgaon,8492.0,1.0,5.0,410.0,Royal Enfield
9338,Royal Enfield Himalayan 410cc,138000.0,Delhi,5000.0,1.0,5.0,410.0,Royal Enfield
9344,Royal Enfield Bullet Twinspark 350cc,80000.0,Delhi,56968.0,1.0,8.0,350.0,Royal Enfield

In [139]:
##bikes based on ages
royal_enfield3=royal_enfield[royal_enfield['age']<=2]

In [140]:
royal_enfield3

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,1.0,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,1.0,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,1.0,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,1.0,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,1.0,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,1.0,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,1.0,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,1.0,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,1.0,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,1.0,2.0,350.0,Royal Enfield

In [141]:
royal_enfield4=royal_enfield[royal_enfield['kms_driven']<=20000]

In [142]:
royal_enfield4

,bike_name,price,city,kms_driven,owner,age,power,brand
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,1.0,4.0,350.0,Royal Enfield
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,1.0,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,2.0,7.0,500.0,Royal Enfield
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,1.0,2.0,500.0,Royal Enfield
42,Royal Enfield Bullet Electra 350cc,78000.0,Lucknow,8500.0,1.0,13.0,350.0,Royal Enfield
...,...,...,...,...,...,...,...,...
9252,Royal Enfield Classic 350cc,100000.0,Ghaziabad,15078.0,1.0,7.0,350.0,Royal Enfield
9254,Royal Enfield Classic Chrome 500cc,105000.0,Gurgaon,15008.0,1.0,9.0,500.0,Royal Enfield
9261,Royal Enfield Classic 500cc,146006.0,Guwahati,8575.0,1.0,4.0,500.0,Royal Enfield
9337,Royal Enfield Himalayan 410cc,120000.0,Gurgaon,8492.0,1.0,5.0,410.0,Royal Enfield
9338,Royal Enfield Himalayan 410cc,138000.0,Delhi,5000.0,1.0,5.0,410.0,Royal Enfield

In [143]:
df[(df['brand']=='Royal Enfield')&(df['age']<=2)&(df['price']<150000)]

,bike_name,price,city,kms_driven,owner,age,power,brand
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,1.0,2.0,350.0,Royal Enfield
1006,Royal Enfield Thunderbird 350cc ABS,148000.0,Haldwani,7300.0,1.0,2.0,350.0,Royal Enfield
1681,Royal Enfield Thunderbird X 350cc ABS,135000.0,Sibsagar,3800.0,1.0,2.0,350.0,Royal Enfield
1716,Royal Enfield Thunderbird 350cc ABS,144700.0,Kharar,770.0,1.0,2.0,350.0,Royal Enfield
1749,Royal Enfield Bullet Twinspark Kickstart 350cc,145000.0,Delhi,5000.0,1.0,2.0,350.0,Royal Enfield
2982,Royal Enfield Classic 350cc-Redditch Edition,137000.0,Sultanpur,8400.0,1.0,2.0,350.0,Royal Enfield
5939,Royal Enfield Bullet Twinspark Kickstart 350cc,105000.0,Faridabad,7255.0,1.0,2.0,350.0,Royal Enfield
6090,Royal Enfield Bullet Electra Twinspark 350CC ABS,127000.0,Mumbai,83.0,1.0,2.0,350.0,Royal Enfield
6298,Royal Enfield Bullet Electra Twinspark 350CC ABS,140000.0,Mumbai,2000.0,1.0,2.0,350.0,Royal Enfield
6329,Royal Enfield Electra 350cc,130000.0,Faridabad,3688.0,1.0,2.0,350.0,Royal Enfield
6590,Royal Enfield Classic 350cc,130000.0,Ghaziabad,19249.0,1.0,2.0,350.0,Royal Enfield
7019,Royal Enfield Electra 350cc,135000.0,Ahmedabad,10779.0,1.0,2.0,350.0,Royal Enfield
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,1.0,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,1.0,2.0,350.0,Royal Enfield

In [144]:
##for extracting information but with the help of query function
df.query("brand=='Royal Enfield' and age<=2")

,bike_name,price,city,kms_driven,owner,age,power,brand
38,Royal Enfield Thunderbird X 500cc,190500.0,Samastipur,4550.0,1.0,2.0,500.0,Royal Enfield
81,Royal Enfield Interceptor 650cc,260000.0,Navi Mumbai,3800.0,1.0,2.0,650.0,Royal Enfield
139,Royal Enfield Himalayan 410cc Fi ABS,173300.0,Vadodara,14000.0,1.0,2.0,410.0,Royal Enfield
194,Royal Enfield Electra 350cc,145000.0,Bangalore,4000.0,1.0,2.0,350.0,Royal Enfield
222,Royal Enfield Himalayan 410cc Fi ABS,177982.0,Hamirpur(hp),7000.0,1.0,2.0,410.0,Royal Enfield
...,...,...,...,...,...,...,...,...
7294,Royal Enfield Classic 350cc-Redditch Edition,133500.0,Mumbai,1608.0,1.0,2.0,350.0,Royal Enfield
7694,Royal Enfield Classic Chrome 500cc ABS,215000.0,Delhi,417.0,1.0,2.0,500.0,Royal Enfield
8139,Royal Enfield Thunderbird X 350cc ABS,169000.0,Bangalore,4411.0,1.0,2.0,350.0,Royal Enfield
8192,Royal Enfield Thunderbird 350cc ABS,145000.0,Ghaziabad,12400.0,1.0,2.0,350.0,Royal Enfield
8836,Royal Enfield Thunderbird X 350cc ABS,170200.0,Mumbai,1000.0,1.0,2.0,350.0,Royal Enfield

In [145]:
df.drop('bike_name',axis=1,inplace=True)

In [ ]:
#df.dropna(inplace='True')

In [153]:
x=df.drop('price',axis=1)
x

           city  kms_driven  owner  age  power            brand
0     Ahmedabad     17654.0    1.0  3.0  110.0              TVS
1         Delhi     11000.0    1.0  4.0  350.0    Royal Enfield
2         Delhi       110.0    1.0  8.0  675.0          Triumph
3     Bangalore     16329.0    1.0  4.0  180.0              TVS
4     Bangalore     10000.0    1.0  3.0  150.0           Yamaha
...         ...         ...    ...  ...    ...              ...
9362      Delhi     48587.0    1.0  8.0  150.0             Hero
9369  Bangalore     60000.0    1.0  9.0  220.0            Bajaj
9370    Jodhpur      3430.0    1.0  4.0  750.0  Harley-Davidson
9371  Hyderabad     21300.0    1.0  4.0  400.0            Bajaj
9372  Hyderabad      7127.0    1.0  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [152]:
y=df[['price']]
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [154]:
df.to_csv("clean_bike_data.csv")